name: run smoke test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.5
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade pipenv==2018.11.26
      - name: Install test dependencies
        run: pipenv install --dev
        working-directory: example
      - name: Run smoke test
        run: pipenv run python example.py
        working-directory: example
        env:
          API_BASE_PATH: "http://test-api.regulaforensics.com"
          TEST_LICENSE: ${{secrets.TEST_LICENSE}}
